; HEADER_BLOCK_START
; generated by Flash Studio 1.7.13 on 2026-08-26 at 21:52:47
; total layer number: 2
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 0.40
; filament: 1
; HEADER_BLOCK_END

; filament used [mm] = 285.52
; filament used [cm3] = 0.69
; filament used [g] = 0.85
; filament cost = 0.02
; total filament used [g] = 0.85
; total filament cost = 0.02
; total layers count = 2
; estimated printing time (normal mode) = 1m 57s
; estimated first layer printing time (normal mode) = 15s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 0
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 100
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; auxiliary_fan = 1
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; bed_temperature_formula = by_highest_temp
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_density = 100%
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 25
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = no_brim
; brim_use_efc_outline = 0
; brim_width = 5
; calib_flowrate_topinfill_special_order = 0
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; complete_print_exhaust_fan_speed = 80
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 55
; cooling_tube_length = 0
; cooling_tube_retraction = 0
; counterbore_hole_bridging = none
; curr_bed_type = Textured PEI Plate
; default_acceleration = 10000
; default_bed_type = 
; default_filament_colour = ""
; default_filament_profile = "Flashforge Generic PLA"
; default_jerk = 0
; default_junction_deviation = 0
; default_nozzle_volume_type = Standard
; default_print_profile = 0.20mm Standard @Flashforge AD5M 0.4 Nozzle
; deretraction_speed = 30
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 60
; elefant_foot_compensation = 0.15
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 1
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 0
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_power_loss_recovery = printer_configuration
; enable_pressure_advance = 1
; enable_prime_tower = 0
; enable_support = 0
; enable_tower_interface_cooldown_during_tower = 0
; enable_tower_interface_features = 0
; enable_wrapping_detection = 0
; enforce_support_layers = 0
; eng_plate_temp = 60
; eng_plate_temp_initial_layer = 55
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 0
; extra_loading_move = 0
; extra_perimeters_on_overhangs = 0
; extra_solid_infills = 
; extruder_ams_count = 1#0|4#0;1#0|4#0
; extruder_clearance_height_to_lid = 150
; extruder_clearance_height_to_rod = 27
; extruder_clearance_radius = 76
; extruder_colour = #26A69A
; extruder_offset = 0x0
; extruder_printable_area = 
; extruder_printable_height = 0
; extruder_type = Direct Drive
; extruder_variant_list = "Direct Drive Standard"
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_adaptive_volumetric_speed = 0
; filament_adhesiveness_category = 0
; filament_change_length = 0
; filament_colour = #26A69A
; filament_colour_type = 1
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode\n"
; filament_extruder_variant = "Direct Drive Standard"
; filament_flow_ratio = 0.98
; filament_flush_temp = 0
; filament_flush_volumetric_speed = 0
; filament_ids = GFL99
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_map = 1
; filament_map_mode = Auto For Flush
; filament_max_volumetric_speed = 25
; filament_minimal_purge_on_wipe_tower = 15
; filament_multi_colour = #26A69A
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_printable = 3
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_self_index = 1
; filament_settings_id = "Flashforge HS PLA"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; filament start gcode\n;right_extruder_material: PLA\n"
; filament_toolchange_delay = 0
; filament_tower_interface_pre_extrusion_dist = 10
; filament_tower_interface_pre_extrusion_length = 0
; filament_tower_interface_print_temp = -1
; filament_tower_interface_purge_volume = 20
; filament_tower_ironing_area = 4
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Flashforge
; file_start_gcode = 
; filename_format = {input_filename_base}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 0.5
; first_layer_flow_ratio = 1
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.3
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = disabled_fuzzy
; fuzzy_skin_first_layer = 0
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.3
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.2
; gap_fill_flow_ratio = 1
; gap_fill_target = nowhere
; gap_infill_speed = 200
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 0
; grab_length = 0
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 50
; hot_plate_temp_initial_layer = 55
; idle_temperature = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_lock_depth = 1
; infill_overhang_angle = 60
; infill_shift_step = 0.4
; infill_wall_overlap = 50%
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 80
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 5000
; inner_wall_flow_ratio = 1
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 300
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1
; internal_bridge_flow = 1
; internal_bridge_speed = 50
; internal_solid_infill_acceleration = 7000
; internal_solid_infill_flow_ratio = 1
; internal_solid_infill_line_width = 0.42
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 250
; ironing_angle = 0
; ironing_angle_fixed = 0
; ironing_fan_speed = -1
; ironing_flow = 15%
; ironing_inset = 0
; ironing_pattern = rectilinear
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = no ironing
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; line_width = 0.42
; long_retractions_when_cut = 0
; long_retractions_when_ec = 0
; machine_end_gcode = G1 E-3 F3600\nG0 X50 Y50 F30000\nM104 S0 ; turn off temperature
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 20000,20000
; machine_max_acceleration_retracting = 5000,5000
; machine_max_acceleration_travel = 20000,20000
; machine_max_acceleration_x = 20000,20000
; machine_max_acceleration_y = 20000,20000
; machine_max_acceleration_z = 500,500
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 9,9
; machine_max_jerk_y = 9,9
; machine_max_jerk_z = 3,3
; machine_max_junction_deviation = 0.01
; machine_max_speed_e = 30,30
; machine_max_speed_x = 600,600
; machine_max_speed_y = 600,600
; machine_max_speed_z = 20,20
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = PAUSE
; machine_start_gcode = M190 S[bed_temperature_initial_layer_single]\nM104 S[nozzle_temperature_initial_layer]\nG90\nM83\nG1 Z5 F6000\nG1 E-0.2 F800\nG1 X110 Y-110 F6000\nG1 E2 F800\nG1 Y-110 X55 Z0.25 F4800\nG1 X-55 E8 F2400\nG1 Y-109.6 F2400\nG1 X55 E5 F2400\nG1 Y-110 X55 Z0.45 F4800\nG1 X-55 E8 F2400\nG1 Y-109.6 F2400\nG1 X55 E5 F2400\nG92 E0
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; master_extruder_id = 1
; max_bridge_length = 10
; max_layer_height = 0.28
; max_resonance_avoidance_speed = 120
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_resonance_avoidance_speed = 70
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_flush_dataset = 0
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 220
; nozzle_temperature_initial_layer = 220
; nozzle_temperature_range_high = 230
; nozzle_temperature_range_low = 190
; nozzle_type = stainless_steel
; nozzle_volume = 0
; nozzle_volume_type = Standard
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 5000
; outer_wall_flow_ratio = 1
; outer_wall_jerk = 9
; outer_wall_line_width = 0.42
; outer_wall_speed = 200
; overhang_1_4_speed = 0
; overhang_2_4_speed = 40
; overhang_3_4_speed = 20
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_flow_ratio = 1
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; parking_pos_retraction = 0
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; physical_extruder_map = 0
; post_process = 
; precise_outer_wall = 1
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.025
; prime_tower_brim_width = 3
; prime_tower_enable_framework = 0
; prime_tower_flat_ironing = 0
; prime_tower_infill_gap = 150%
; prime_tower_skip_points = 1
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = "Flashforge Adventurer 5M 0.4 Nozzle"
; print_extruder_id = 1
; print_extruder_variant = "Direct Drive Standard"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @Flashforge AD5M 0.4 Nozzle
; printable_area = -110x-110,110x-110,110x110,-110x110
; printable_height = 220
; printer_agent = 
; printer_extruder_id = 1
; printer_extruder_variant = "Direct Drive Standard"
; printer_model = Flashforge Adventurer 5M
; printer_notes = 
; printer_settings_id = Flashforge Adventurer 5M 0.4 Nozzle
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; resonance_avoidance = 0
; retract_before_wipe = 100%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_distances_when_ec = 10
; retraction_length = 0.8
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; set_other_flow_ratios = 0
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; single_loop_draft_shield = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 6
; slow_down_layers = 1
; slow_down_min_speed = 20
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; solid_infill_rotate_template = 
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_flow_ratio = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = grid
; sparse_infill_rotate_template = 
; sparse_infill_speed = 270
; spiral_finishing_flow_ratio = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 35
; supertack_plate_temp_initial_layer = 35
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.18
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_flow_ratio = 1
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_flow_ratio = 1
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = rectilinear
; support_ironing_spacing = 0.1
; support_line_width = 0.42
; support_material_interface_fan_speed = 100
; support_multi_bed_types = 1
; support_object_first_layer_gap = 0.2
; support_object_skip_flush = 0
; support_object_xy_distance = 0.3
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_threshold_overlap = 50%
; support_top_z_distance = 0.18
; support_type = normal(auto)
; symmetric_infill_y_axis = 0
; temperature_vitrification = 60
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 55
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 140x110/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 5
; top_shell_thickness = 1
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 2000
; top_surface_density = 100%
; top_surface_jerk = 9
; top_surface_line_width = 0.42
; top_surface_pattern = monotonicline
; top_surface_speed = 200
; travel_acceleration = 10000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 500
; travel_speed_z = 0
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 5
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; volumetric_speed_coefficients = ""
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_loops = 2
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 2
; wipe_on_loops = 0
; wipe_speed = 200
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 30
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_rib_length = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_fillet_wall = 1
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rib_width = 8
; wipe_tower_rotation_angle = 0
; wipe_tower_type = type1
; wipe_tower_wall_type = rectangle
; wipe_tower_x = 46.000
; wipe_tower_x = 46
; wipe_tower_y = 100.375
; wipe_tower_y = 100.375
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; wrapping_detection_gcode = 
; wrapping_detection_layers = 20
; wrapping_exclude_area = 
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Auto Lift
; z_offset = 0
; first_layer_bed_temperature = 55
; bed_shape = -110x-110,110x-110,110x110,-110x110
; first_layer_temperature = 220
; first_layer_height = 0.200
; CONFIG_BLOCK_END


; THUMBNAIL_BLOCK_START

;
; thumbnail begin 140x110 960
; iVBORw0KGgoAAAANSUhEUgAAAIwAAABuCAYAAAD1TPu3AAAClklEQVR4Ae3cv4pUMRTA4dRiJZZiYy
; dYCL6DlZWdb2EnVvME9j7tyAjDXnbnz72Z5CYn+T44D7DJj0MuupsSAAAAQFlvvn09JLjnw98/x/OI
; hpuWsQiHq66FIhpeWBPLMhrhTOp08VtisW0mlhuKaCZUIhbhTKB0KKIZWM1YPIgH8sjD1raZzN6h2D
; aBtYzFtgmkl1BEE0CPsQinQy0etqIJKkooz6MRzs4ibRXbprFIUYimsUgxCKehSJcvmsYiXXqJaIST
; aYSHrW2zk0iXWzMa4awQ6VL3CifxUqRLFE1jkS5POA3N/LAVzUaRLqnHaKYKJ9Ll9B5OGlmkyxBNY5
; EuQTgNRTp00TQW6bBHiiZcOD6X+wgnRRDpUEXTWKTDFE5DkQ5PNI1FOjTTMBwPW9GsFulwzPVodgkn
; 0qGYdeGkGiIdgmkcTaQf3jQMx8NWNLaKWRXN6nBsFXOeu9G8P/wK9QOZ+nMzmtdfPh9EY5bz9sf3Y7
; pHNGZVKLaNyYpFNHPOu98/j68+fTykR52iEc7Yk71VrrFtxpzTVikey5JoxpmqoSzZNmIRzUShFHnY
; 5vIgjhVL6oFt0/dUf9jmsm36my5DWbJtxJJFNELZzLYRy2ai2We6fdjm8iCuN0OFsmTbiCWLaISymW
; 0jls1Esz2Upv8O1AsP4nWxJJ7YNpdnuM/l0kTzNEJZybYRS5YZoxHKg2baNmIpZPRoPGwrGfHzWyiV
; jbRtxLKjyNEIpZGI20YsjUWJptgvulNGzw9iW6VTvW0bn8tB9BCNUIJpuW3EEtTe0fgPToM4/enQ2u
; HYKoOptW08bAdX8vNbKJMosW3EMqGcaIQyuS3bRiz8dy8aD1suuvQgFgo3nbeNrQIAAABAS/8AUTdH
; PWYbI1YAAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.42mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
M73 P0 R1
M106 S0
M106 P2 S0
;TYPE:Custom
M190 S55
M104 S220
G90
M83
G1 Z5 F6000
G1 E-0.2 F800
G1 X110 Y-110 F6000
G1 E2 F800
M73 P1 R1
G1 Y-110 X55 Z0.25 F4800
G1 X-55 E8 F2400
M73 P2 R1
G1 Y-109.6 F2400
M73 P4 R1
G1 X55 E5 F2400
G1 Y-110 X55 Z0.45 F4800
M73 P7 R1
G1 X-55 E8 F2400
G1 Y-109.6 F2400
M73 P9 R1
G1 X55 E5 F2400
G92 E0
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
;right_extruder_material: PLA
SET_PRESSURE_ADVANCE ADVANCE=0.025; Override pressure advance value
M106 S0
M106 P2 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G1 E-.8 F1800
M73 P11 R1
;AFTER_LAYER_CHANGE
;0.2
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=500
G1 X19.1 Y19.1 F30000
G1 Z.6
M73 P12 R1
G1 Z.2
G1 E.8 F1800
;TYPE:Inner wall
;WIDTH:0.5
G1 F3000
G1 X-19.1 Y19.1 E1.4228
G1 X-19.1 Y-19.1 E1.4228
M73 P13 R1
G1 X19.1 Y-19.1 E1.4228
M73 P14 R1
G1 X19.1 Y19.06 E1.42131
G1 X19.6 Y19.6 F30000
M73 P15 R1
;TYPE:Outer wall
G1 F3000
G1 X-19.6 Y19.6 E1.46005
G1 X-19.6 Y-19.6 E1.46005
M73 P16 R1
G1 X19.6 Y-19.6 E1.46005
M73 P17 R1
G1 X19.6 Y19.56 E1.45856
G1 E-.8 F1800
M73 P18 R1
;WIPE_START
G1 F3000
G1 X17.6 Y19.562
;WIPE_END
G1 X17.686 Y11.93 Z.6 F30000
G1 X18.035 Y-18.963 Z.6
G1 Z.2
M73 P19 R1
G1 E.8 F1800
;TYPE:Bottom surface
;WIDTH:0.501892
G1 F4800
G1 X18.757 Y-18.241 E.0382
G1 X18.757 Y-17.591 E.02428
G1 X17.591 Y-18.757 E.06166
G1 X16.942 Y-18.757 E.02428
G1 X18.757 Y-16.942 E.09599
G1 X18.757 Y-16.293 E.02428
G1 X16.293 Y-18.757 E.13032
G1 X15.644 Y-18.757 E.02428
G1 X18.757 Y-15.644 E.16465
G1 X18.757 Y-14.995 E.02428
G1 X14.995 Y-18.757 E.19898
M73 P20 R1
G1 X14.346 Y-18.757 E.02428
G1 X18.757 Y-14.346 E.23331
G1 X18.757 Y-13.697 E.02428
G1 X13.697 Y-18.757 E.26765
G1 X13.048 Y-18.757 E.02428
G1 X18.757 Y-13.048 E.30198
G1 X18.757 Y-12.399 E.02428
G1 X12.399 Y-18.757 E.33631
G1 X11.75 Y-18.757 E.02428
M73 P21 R1
G1 X18.757 Y-11.75 E.37064
G1 X18.757 Y-11.101 E.02428
G1 X11.101 Y-18.757 E.40497
G1 X10.452 Y-18.757 E.02428
G1 X18.757 Y-10.452 E.4393
G1 X18.757 Y-9.802 E.02428
G1 X9.802 Y-18.757 E.47363
G1 X9.153 Y-18.757 E.02428
M73 P22 R1
G1 X18.757 Y-9.153 E.50797
G1 X18.757 Y-8.504 E.02428
G1 X8.504 Y-18.757 E.5423
G1 X7.855 Y-18.757 E.02428
G1 X18.757 Y-7.855 E.57663
G1 X18.757 Y-7.206 E.02428
M73 P23 R1
G1 X7.206 Y-18.757 E.61096
G1 X6.557 Y-18.757 E.02428
G1 X18.757 Y-6.557 E.64529
G1 X18.757 Y-5.908 E.02428
G1 X5.908 Y-18.757 E.67962
G1 X5.259 Y-18.757 E.02428
M73 P24 R1
G1 X18.757 Y-5.259 E.71395
G1 X18.757 Y-4.61 E.02428
G1 X4.61 Y-18.757 E.74829
G1 X3.961 Y-18.757 E.02428
G1 X18.757 Y-3.961 E.78262
G1 X18.757 Y-3.312 E.02428
M73 P25 R1
G1 X3.312 Y-18.757 E.81695
G1 X2.663 Y-18.757 E.02428
G1 X18.757 Y-2.663 E.85128
G1 X18.757 Y-2.013 E.02428
G1 X2.013 Y-18.757 E.88561
G1 X1.364 Y-18.757 E.02428
M73 P26 R1
G1 X18.757 Y-1.364 E.91994
G1 X18.757 Y-.715 E.02428
G1 X.715 Y-18.757 E.95427
G1 X.066 Y-18.757 E.02428
M73 P27 R1
G1 X18.757 Y-.066 E.98861
G1 X18.757 Y.583 E.02428
G1 X-.583 Y-18.757 E1.02294
G1 X-1.232 Y-18.757 E.02428
G1 X18.757 Y1.232 E1.05727
G1 X18.757 Y1.881 E.02428
M73 P28 R1
G1 X-1.881 Y-18.757 E1.0916
G1 X-2.53 Y-18.757 E.02428
G1 X18.757 Y2.53 E1.12593
G1 X18.757 Y3.179 E.02428
M73 P29 R1
G1 X-3.179 Y-18.757 E1.16026
G1 X-3.828 Y-18.757 E.02428
G1 X18.757 Y3.828 E1.1946
G1 X18.757 Y4.477 E.02428
M73 P30 R1
G1 X-4.477 Y-18.757 E1.22893
G1 X-5.126 Y-18.757 E.02428
G1 X18.757 Y5.126 E1.26326
G1 X18.757 Y5.776 E.02428
M73 P31 R1
G1 X-5.776 Y-18.757 E1.29759
G1 X-6.425 Y-18.757 E.02428
G1 X18.757 Y6.425 E1.33192
G1 X18.757 Y7.074 E.02428
M73 P32 R1
G1 X-7.074 Y-18.757 E1.36625
G1 X-7.723 Y-18.757 E.02428
G1 X18.757 Y7.723 E1.40058
G1 X18.757 Y8.372 E.02428
M73 P33 R1
G1 X-8.372 Y-18.757 E1.43492
G1 X-9.021 Y-18.757 E.02428
G1 X18.757 Y9.021 E1.46925
M73 P34 R1
G1 X18.757 Y9.67 E.02428
G1 X-9.67 Y-18.757 E1.50358
G1 X-10.319 Y-18.757 E.02428
M73 P35 R1
G1 X18.757 Y10.319 E1.53791
G1 X18.757 Y10.968 E.02428
G1 X-10.968 Y-18.757 E1.57224
G1 X-11.617 Y-18.757 E.02428
M73 P36 R1
G1 X18.757 Y11.617 E1.60657
G1 X18.757 Y12.266 E.02428
G1 X-12.266 Y-18.757 E1.6409
G1 X-12.915 Y-18.757 E.02428
M73 P37 R1
G1 X18.757 Y12.915 E1.67524
G1 X18.757 Y13.565 E.02428
M73 P38 R1
G1 X-13.565 Y-18.757 E1.70957
G1 X-14.214 Y-18.757 E.02428
G1 X18.757 Y14.214 E1.7439
G1 X18.757 Y14.863 E.02428
M73 P39 R1
G1 X-14.863 Y-18.757 E1.77823
G1 X-15.512 Y-18.757 E.02428
M73 P40 R1
G1 X18.757 Y15.512 E1.81256
G1 X18.757 Y16.161 E.02428
G1 X-16.161 Y-18.757 E1.84689
G1 X-16.81 Y-18.757 E.02428
M73 P41 R1
G1 X18.757 Y16.81 E1.88122
G1 X18.757 Y17.459 E.02428
M73 P42 R1
G1 X-17.459 Y-18.757 E1.91556
G1 X-18.108 Y-18.757 E.02428
G1 X18.757 Y18.108 E1.94989
G1 X18.757 Y18.757 E.02427
M73 P43 R1
G1 X-18.757 Y-18.757 E1.98422
G1 X-18.757 Y-18.108 E.02428
M73 P44 R1
G1 X18.108 Y18.757 E1.94988
G1 X17.459 Y18.757 E.02428
G1 X-18.757 Y-17.459 E1.91555
G1 X-18.757 Y-16.81 E.02428
M73 P45 R1
G1 X16.81 Y18.757 E1.88122
G1 X16.161 Y18.757 E.02428
M73 P46 R1
G1 X-18.757 Y-16.161 E1.84689
G1 X-18.757 Y-15.512 E.02428
G1 X15.512 Y18.757 E1.81256
M73 P47 R1
G1 X14.863 Y18.757 E.02428
G1 X-18.757 Y-14.863 E1.77822
G1 X-18.757 Y-14.214 E.02428
M73 P48 R1
G1 X14.214 Y18.757 E1.74389
G1 X13.564 Y18.757 E.02428
G1 X-18.757 Y-13.564 E1.70956
G1 X-18.757 Y-12.915 E.02428
M73 P49 R0
G1 X12.915 Y18.757 E1.67523
G1 X12.266 Y18.757 E.02428
M73 P50 R0
G1 X-18.757 Y-12.266 E1.6409
G1 X-18.757 Y-11.617 E.02428
G1 X11.617 Y18.757 E1.60657
G1 X10.968 Y18.757 E.02428
M73 P51 R0
G1 X-18.757 Y-10.968 E1.57224
G1 X-18.757 Y-10.319 E.02428
G1 X10.319 Y18.757 E1.5379
M73 P52 R0
G1 X9.67 Y18.757 E.02428
G1 X-18.757 Y-9.67 E1.50357
G1 X-18.757 Y-9.021 E.02428
M73 P53 R0
G1 X9.021 Y18.757 E1.46924
G1 X8.372 Y18.757 E.02428
G1 X-18.757 Y-8.372 E1.43491
G1 X-18.757 Y-7.723 E.02428
M73 P54 R0
G1 X7.723 Y18.757 E1.40058
G1 X7.074 Y18.757 E.02428
G1 X-18.757 Y-7.074 E1.36625
G1 X-18.757 Y-6.425 E.02428
M73 P55 R0
G1 X6.425 Y18.757 E1.33192
G1 X5.775 Y18.757 E.02428
G1 X-18.757 Y-5.775 E1.29758
G1 X-18.757 Y-5.126 E.02428
M73 P56 R0
G1 X5.126 Y18.757 E1.26325
G1 X4.477 Y18.757 E.02428
G1 X-18.757 Y-4.477 E1.22892
G1 X-18.757 Y-3.828 E.02428
M73 P57 R0
G1 X3.828 Y18.757 E1.19459
G1 X3.179 Y18.757 E.02428
G1 X-18.757 Y-3.179 E1.16026
G1 X-18.757 Y-2.53 E.02428
M73 P58 R0
G1 X2.53 Y18.757 E1.12593
G1 X1.881 Y18.757 E.02428
G1 X-18.757 Y-1.881 E1.0916
G1 X-18.757 Y-1.232 E.02428
M73 P59 R0
G1 X1.232 Y18.757 E1.05726
G1 X.583 Y18.757 E.02428
G1 X-18.757 Y-.583 E1.02293
G1 X-18.757 Y.066 E.02428
M73 P60 R0
G1 X-.066 Y18.757 E.9886
G1 X-.715 Y18.757 E.02428
G1 X-18.757 Y.715 E.95427
G1 X-18.757 Y1.364 E.02428
M73 P61 R0
G1 X-1.364 Y18.757 E.91994
G1 X-2.014 Y18.757 E.02428
G1 X-18.757 Y2.014 E.88561
G1 X-18.757 Y2.663 E.02428
G1 X-2.663 Y18.757 E.85128
G1 X-3.312 Y18.757 E.02428
M73 P62 R0
G1 X-18.757 Y3.312 E.81694
G1 X-18.757 Y3.961 E.02428
G1 X-3.961 Y18.757 E.78261
G1 X-4.61 Y18.757 E.02428
G1 X-18.757 Y4.61 E.74828
M73 P63 R0
G1 X-18.757 Y5.259 E.02428
G1 X-5.259 Y18.757 E.71395
G1 X-5.908 Y18.757 E.02428
G1 X-18.757 Y5.908 E.67962
G1 X-18.757 Y6.557 E.02428
M73 P64 R0
G1 X-6.557 Y18.757 E.64529
G1 X-7.206 Y18.757 E.02428
G1 X-18.757 Y7.206 E.61095
G1 X-18.757 Y7.855 E.02428
G1 X-7.855 Y18.757 E.57662
G1 X-8.504 Y18.757 E.02428
G1 X-18.757 Y8.504 E.54229
M73 P65 R0
G1 X-18.757 Y9.153 E.02428
G1 X-9.153 Y18.757 E.50796
G1 X-9.803 Y18.757 E.02428
G1 X-18.757 Y9.803 E.47363
G1 X-18.757 Y10.452 E.02428
G1 X-10.452 Y18.757 E.4393
G1 X-11.101 Y18.757 E.02428
M73 P66 R0
G1 X-18.757 Y11.101 E.40497
G1 X-18.757 Y11.75 E.02428
G1 X-11.75 Y18.757 E.37063
G1 X-12.399 Y18.757 E.02428
G1 X-18.757 Y12.399 E.3363
G1 X-18.757 Y13.048 E.02428
G1 X-13.048 Y18.757 E.30197
G1 X-13.697 Y18.757 E.02428
M73 P67 R0
G1 X-18.757 Y13.697 E.26764
G1 X-18.757 Y14.346 E.02428
G1 X-14.346 Y18.757 E.23331
G1 X-14.995 Y18.757 E.02428
G1 X-18.757 Y14.995 E.19898
G1 X-18.757 Y15.644 E.02428
G1 X-15.644 Y18.757 E.16465
G1 X-16.293 Y18.757 E.02428
G1 X-18.757 Y16.293 E.13031
G1 X-18.757 Y16.943 E.02428
M73 P68 R0
G1 X-16.943 Y18.757 E.09598
G1 X-17.592 Y18.757 E.02428
G1 X-18.757 Y17.592 E.06165
G1 X-18.757 Y18.241 E.02428
G1 X-18.035 Y18.963 E.0382
M106 S255
M106 P2 S255
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.4
G1 E-.8 F1800
;WIPE_START
G1 F4800
G1 X-18.757 Y18.241
G1 X-18.757 Y17.592
G1 X-18.524 Y17.825
;WIPE_END
;AFTER_LAYER_CHANGE
;0.4
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=10000
M140 S60 ; set bed temperature
G17
G3 Z.8 I-.049 J1.216 P1  F30000
G1 X19.355 Y19.355 Z.8
G1 Z.4
G1 E.8 F1800
SET_VELOCITY_LIMIT ACCEL=5000
;TYPE:Inner wall
;WIDTH:0.45
G1 F18000
G1 X-19.355 Y19.355 E1.28408
G1 X-19.355 Y-19.355 E1.28408
M73 P69 R0
G1 X19.355 Y-19.355 E1.28408
G1 X19.355 Y19.315 E1.28275
G1 X19.79 Y19.79 F30000
;TYPE:Outer wall
;WIDTH:0.42
G1 F12000
G1 X-19.79 Y19.79 E1.21618
G1 X-19.79 Y-19.79 E1.21618
G1 X19.79 Y-19.79 E1.21618
G1 X19.79 Y19.75 E1.21495
M73 P70 R0
SET_VELOCITY_LIMIT ACCEL=10000
G1 E-.8 F1800
;WIPE_START
G1 F12000
G1 X17.79 Y19.752
;WIPE_END
G1 X19.231 Y18.466 Z.8 F30000
G1 Z.4
G1 E.8 F1800
SET_VELOCITY_LIMIT ACCEL=2000
;TYPE:Top surface
;WIDTH:0.421015
G1 F12000
G1 X18.466 Y19.231 E.03331
SET_VELOCITY_LIMIT ACCEL=10000
G1 X17.932 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y17.931 E.05661
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y17.397 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X17.397 Y19.231 E.0799
SET_VELOCITY_LIMIT ACCEL=10000
G1 X16.862 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y16.862 E.1032
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y16.327 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X16.327 Y19.231 E.1265
SET_VELOCITY_LIMIT ACCEL=10000
G1 X15.793 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y15.793 E.1498
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y15.258 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X15.258 Y19.231 E.1731
SET_VELOCITY_LIMIT ACCEL=10000
G1 X14.723 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y14.723 E.19639
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y14.189 F30000
M73 P71 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X14.189 Y19.231 E.21969
SET_VELOCITY_LIMIT ACCEL=10000
G1 X13.654 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y13.654 E.24299
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y13.119 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X13.119 Y19.231 E.26629
SET_VELOCITY_LIMIT ACCEL=10000
G1 X12.584 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y12.584 E.28959
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y12.05 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X12.05 Y19.231 E.31289
SET_VELOCITY_LIMIT ACCEL=10000
G1 X11.515 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y11.515 E.33618
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y10.98 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X10.98 Y19.231 E.35948
SET_VELOCITY_LIMIT ACCEL=10000
G1 X10.446 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y10.446 E.38278
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y9.911 F30000
M73 P72 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X9.911 Y19.231 E.40608
SET_VELOCITY_LIMIT ACCEL=10000
G1 X9.376 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y9.376 E.42938
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y8.841 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X8.841 Y19.231 E.45267
SET_VELOCITY_LIMIT ACCEL=10000
G1 X8.307 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y8.307 E.47597
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y7.772 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X7.772 Y19.231 E.49927
SET_VELOCITY_LIMIT ACCEL=10000
G1 X7.237 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y7.237 E.52257
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y6.703 F30000
M73 P73 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X6.703 Y19.231 E.54587
SET_VELOCITY_LIMIT ACCEL=10000
G1 X6.168 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y6.168 E.56917
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y5.633 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X5.633 Y19.231 E.59246
SET_VELOCITY_LIMIT ACCEL=10000
G1 X5.099 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y5.099 E.61576
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y4.564 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X4.564 Y19.231 E.63906
SET_VELOCITY_LIMIT ACCEL=10000
G1 X4.029 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y4.029 E.66236
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y3.494 F30000
M73 P74 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X3.494 Y19.231 E.68566
SET_VELOCITY_LIMIT ACCEL=10000
G1 X2.96 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y2.96 E.70895
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y2.425 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X2.425 Y19.231 E.73225
SET_VELOCITY_LIMIT ACCEL=10000
G1 X1.89 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y1.89 E.75555
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y1.356 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X1.356 Y19.231 E.77885
SET_VELOCITY_LIMIT ACCEL=10000
G1 X.821 Y19.231 F30000
M73 P75 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y.821 E.80215
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y.286 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X.286 Y19.231 E.82545
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-.249 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-.249 E.84874
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-.783 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-.783 Y19.231 E.87204
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-1.318 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-1.318 E.89534
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-1.853 F30000
M73 P76 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-1.853 Y19.231 E.91864
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-2.387 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-2.387 E.94194
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-2.922 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-2.922 Y19.231 E.96523
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-3.457 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-3.457 E.98853
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-3.991 F30000
M73 P77 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-3.991 Y19.231 E1.01183
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-4.526 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-4.526 E1.03513
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-5.061 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-5.061 Y19.231 E1.05843
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-5.596 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-5.596 E1.08173
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-6.13 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-6.13 Y19.231 E1.10502
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-6.665 Y19.231 F30000
M73 P78 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-6.665 E1.12832
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-7.2 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-7.2 Y19.231 E1.15162
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-7.734 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-7.734 E1.17492
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-8.269 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-8.269 Y19.231 E1.19822
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-8.804 Y19.231 F30000
M73 P79 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-8.804 E1.22151
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-9.339 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-9.339 Y19.231 E1.24481
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-9.873 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-9.873 E1.26811
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-10.408 F30000
M73 P80 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-10.408 Y19.231 E1.29141
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-10.943 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-10.943 E1.31471
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-11.477 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-11.477 Y19.231 E1.33801
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-12.012 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-12.012 E1.3613
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-12.547 F30000
M73 P81 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-12.547 Y19.231 E1.3846
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-13.082 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-13.082 E1.4079
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-13.616 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-13.616 Y19.231 E1.4312
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-14.151 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-14.151 E1.4545
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-14.686 F30000
M73 P82 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-14.686 Y19.231 E1.47779
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-15.22 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-15.22 E1.50109
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-15.755 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-15.755 Y19.231 E1.52439
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-16.29 Y19.231 F30000
M73 P83 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-16.29 E1.54769
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-16.824 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-16.824 Y19.231 E1.57099
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-17.359 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-17.359 E1.59429
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-17.894 F30000
M73 P84 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-17.894 Y19.231 E1.61758
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-18.429 Y19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X19.231 Y-18.429 E1.64088
SET_VELOCITY_LIMIT ACCEL=10000
G1 X19.231 Y-18.963 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-18.963 Y19.231 E1.66418
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y18.963 F30000
M73 P85 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X18.963 Y-19.231 E1.66418
SET_VELOCITY_LIMIT ACCEL=10000
G1 X18.429 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y18.429 E1.64088
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y17.894 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X17.894 Y-19.231 E1.61758
SET_VELOCITY_LIMIT ACCEL=10000
G1 X17.359 Y-19.231 F30000
M73 P86 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y17.359 E1.59428
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y16.824 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X16.824 Y-19.231 E1.57099
SET_VELOCITY_LIMIT ACCEL=10000
G1 X16.29 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y16.29 E1.54769
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y15.755 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X15.755 Y-19.231 E1.52439
SET_VELOCITY_LIMIT ACCEL=10000
G1 X15.22 Y-19.231 F30000
M73 P87 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y15.22 E1.50109
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y14.686 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X14.686 Y-19.231 E1.47779
SET_VELOCITY_LIMIT ACCEL=10000
G1 X14.151 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y14.151 E1.45449
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y13.616 F30000
M73 P88 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X13.616 Y-19.231 E1.4312
SET_VELOCITY_LIMIT ACCEL=10000
G1 X13.081 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y13.081 E1.4079
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y12.547 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X12.547 Y-19.231 E1.3846
SET_VELOCITY_LIMIT ACCEL=10000
G1 X12.012 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y12.012 E1.3613
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y11.477 F30000
M73 P89 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X11.477 Y-19.231 E1.338
SET_VELOCITY_LIMIT ACCEL=10000
G1 X10.943 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y10.943 E1.31471
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y10.408 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X10.408 Y-19.231 E1.29141
SET_VELOCITY_LIMIT ACCEL=10000
G1 X9.873 Y-19.231 F30000
M73 P90 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y9.873 E1.26811
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y9.339 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X9.339 Y-19.231 E1.24481
SET_VELOCITY_LIMIT ACCEL=10000
G1 X8.804 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y8.804 E1.22151
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y8.269 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X8.269 Y-19.231 E1.19821
SET_VELOCITY_LIMIT ACCEL=10000
G1 X7.734 Y-19.231 F30000
M73 P91 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y7.734 E1.17492
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y7.2 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X7.2 Y-19.231 E1.15162
SET_VELOCITY_LIMIT ACCEL=10000
G1 X6.665 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y6.665 E1.12832
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y6.13 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X6.13 Y-19.231 E1.10502
SET_VELOCITY_LIMIT ACCEL=10000
G1 X5.596 Y-19.231 F30000
M73 P92 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y5.596 E1.08172
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y5.061 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X5.061 Y-19.231 E1.05843
SET_VELOCITY_LIMIT ACCEL=10000
G1 X4.526 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y4.526 E1.03513
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y3.991 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X3.991 Y-19.231 E1.01183
SET_VELOCITY_LIMIT ACCEL=10000
G1 X3.457 Y-19.231 F30000
M73 P93 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y3.457 E.98853
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y2.922 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X2.922 Y-19.231 E.96523
SET_VELOCITY_LIMIT ACCEL=10000
G1 X2.387 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y2.387 E.94193
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y1.853 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X1.853 Y-19.231 E.91864
SET_VELOCITY_LIMIT ACCEL=10000
G1 X1.318 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y1.318 E.89534
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y.783 F30000
M73 P94 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X.783 Y-19.231 E.87204
SET_VELOCITY_LIMIT ACCEL=10000
G1 X.249 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y.249 E.84874
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-.286 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-.286 Y-19.231 E.82544
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-.821 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-.821 E.80215
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-1.356 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-1.356 Y-19.231 E.77885
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-1.89 Y-19.231 F30000
M73 P95 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-1.89 E.75555
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-2.425 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-2.425 Y-19.231 E.73225
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-2.96 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-2.96 E.70895
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-3.494 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-3.494 Y-19.231 E.68565
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-4.029 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-4.029 E.66236
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-4.564 F30000
M73 P96 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-4.564 Y-19.231 E.63906
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-5.099 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-5.099 E.61576
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-5.633 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-5.633 Y-19.231 E.59246
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-6.168 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-6.168 E.56916
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-6.703 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-6.703 Y-19.231 E.54587
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-7.237 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-7.237 E.52257
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-7.772 F30000
M73 P97 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-7.772 Y-19.231 E.49927
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-8.307 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-8.307 E.47597
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-8.842 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-8.842 Y-19.231 E.45267
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-9.376 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-9.376 E.42937
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-9.911 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-9.911 Y-19.231 E.40608
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-10.446 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-10.446 E.38278
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-10.98 F30000
M73 P98 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-10.98 Y-19.231 E.35948
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-11.515 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-11.515 E.33618
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-12.05 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-12.05 Y-19.231 E.31288
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-12.584 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-12.584 E.28959
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-13.119 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-13.119 Y-19.231 E.26629
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-13.654 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-13.654 E.24299
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-14.189 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-14.189 Y-19.231 E.21969
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-14.723 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-14.723 E.19639
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-15.258 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-15.258 Y-19.231 E.17309
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-15.793 Y-19.231 F30000
M73 P99 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-15.793 E.1498
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-16.327 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-16.327 Y-19.231 E.1265
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-16.862 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-16.862 E.1032
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-17.397 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-17.397 Y-19.231 E.0799
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-17.932 Y-19.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-19.231 Y-17.932 E.0566
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-19.231 Y-18.466 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F12000
G1 X-18.466 Y-19.231 E.03331
G1 E-.8 F1800
;WIPE_START
G1 F12000
G1 X-19.231 Y-18.466
;WIPE_END
M106 S0
M106 P2 S0
;TYPE:Custom
; filament end gcode
G1 E-3 F3600
G0 X50 Y50 F30000
M104 S0 ; turn off temperature
M73 P100 R0
; EXECUTABLE_BLOCK_END

